using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Xml.Linq;

namespace KiCad2Gcode
{
    internal class GCodeGenerator
    {
        Configuration config;

        string F = "F3";
        IFormatProvider I = CultureInfo.CreateSpecificCulture("en-US");
        public GCodeGenerator(Configuration config_)
        {
            this.config = config_;
        }

        private void AddToolChange(StreamWriter file, int toolNumber, double spindleSpeed, string comment)
        {
            file.WriteLine("(Tool change : " + comment + " )");
            file.WriteLine("M5");
            file.WriteLine("M6 T" + toolNumber.ToString());
            file.WriteLine("G43 H" + toolNumber.ToString());
            file.WriteLine("M3 S"+ spindleSpeed.ToString("F0"));
            if(config.m3dwel > 0)
            {
                file.WriteLine("G4 P" + config.m3dwel.ToString("F0"));
            }
            file.WriteLine("G0 Z" + config.clearLevel.ToString(F,I));
        }

        private void AddStopTool(StreamWriter file)
        {
            file.WriteLine("(Tool stop)");
            file.WriteLine("M5");
        }

        private void GeneratePath(StreamWriter file, Polygon polygon, double feedRate)
        {
            Point2D startPt = polygon.points.Last.Value.pt;

            LinkedListNode<Node> nll = polygon.points.First;
            while(nll != null)
            {
                Node n = nll.Value;
                if(n.arc == null)
                {
                    file.WriteLine("G1 X" + n.pt.x.ToString(F,I ) + " Y" + n.pt.y.ToString(F,I) + " F" + feedRate.ToString(F,I));
                }
                else
                {
                    double cx = n.arc.centre.x - startPt.x;
                    double cy = n.arc.centre.y - startPt.y;

                    string instruction = n.arc.ccw ? "G3" : "G2";

                    string epStr = "";

                    if(n.pt.IsSameAs(startPt) == false)
                    {
                        epStr = " X" + n.pt.x.ToString(F,I) + " Y" + n.pt.y.ToString(F,I);
                    }

                    string commentStr = " ( cX" + n.arc.centre.x.ToString(F,I) + " cY" + n.arc.centre.y.ToString(F,I) + " )";

                    file.WriteLine(instruction + " I" + cx.ToString(F,I) + " J" +  cy.ToString(F,I) + epStr + " F" + feedRate.ToString(F,I) + commentStr);
                }
                startPt = n.pt;
                nll = nll.Next;
            }
        }

        public void Generate(string fileName, List<DrillList> drills, List<Polygon> traces, List<Polygon> cuts, Polygon outerCut)
        {
            /*create file */
            StreamWriter file = File.CreateText(fileName);
            if(file == null)
            {
                return;
            }


            /* generate preamble */
            file.WriteLine("Generated by KiCAD2GCode");
            file.WriteLine("(begin preamble)");
            file.WriteLine("G17 G54 G40 G49 G80 G90");
            file.WriteLine("G21");
            file.WriteLine("G0 Z" + config.clearLevel.ToString(F,I)) ;

            /*generate drills */
            if (config.drillAcive)
            {
                foreach (DrillList drill in drills)
                {
                    AddToolChange(file, drill.drillData.toolNumber, drill.drillData.spindleSpeed, "drill " + drill.drillData.diameter.ToString(F,I) + "[mm]");
                    file.WriteLine("(start drilling)");
                    foreach (Point2D p in drill.pts)
                    {
                        file.WriteLine("G0 X" + p.x.ToString(F,I) + " Y" + p.y.ToString(F,I));
                        file.WriteLine("G0 Z" + config.safeLevel.ToString(F,I));
                        file.WriteLine("G81 X" + p.x.ToString(F,I) + " Y" + p.y.ToString(F,I) + " Z" + config.drillLevel.ToString(F,I) + " R" + config.safeLevel.ToString(F,I) + " F" + drill.drillData.feedRate.ToString(F,I));
                    }
                    file.WriteLine("(stop drilling)");
                    file.WriteLine("G80");
                    file.WriteLine("G0 Z" + config.clearLevel.ToString(F,I));
                    AddStopTool(file);
                }
            }


            /*generate traces*/

            if(traces != null && traces.Count > 0 && config.traceActive)
            {
                AddToolChange(file, config.traceMillToolNumber, config.traceMillSpindleSpeed, "mill tool");
                file.WriteLine("(start traces milling)");

                foreach(Polygon polygon in traces)
                {
                    file.WriteLine("G0 X" + polygon.points.Last.Value.pt.x.ToString(F,I) + " Y" + polygon.points.Last.Value.pt.y.ToString(F,I));
                    file.WriteLine("G0 Z" + config.safeLevel.ToString(F,I));
                    file.WriteLine("G1 Z" + config.traceMillLevel.ToString(F,I) + " F" + config.traceMillVFeedRate.ToString(F,I));

                    GeneratePath(file, polygon, config.traceMillHFeedRate);

                    file.WriteLine("G0 Z" + config.clearLevel.ToString(F,I));
                }
                

                file.WriteLine("(stop traces milling)");
                AddStopTool(file);
            }
            /*generate board holes */
            if(cuts != null && cuts.Count> 0 && config.boardHolesActive)
            {
                AddToolChange(file, config.traceMillToolNumber, config.traceMillSpindleSpeed, "mill tool");
                file.WriteLine("(start holes milling)");

                foreach (Polygon polygon in cuts)
                {
                    file.WriteLine("G0 X" + polygon.points.Last.Value.pt.x.ToString(F,I) + " Y" + polygon.points.Last.Value.pt.y.ToString(F,I));
                    file.WriteLine("G0 Z" + config.safeLevel.ToString(F,I));
                    file.WriteLine("G1 Z" + config.boardMillLevel.ToString(F,I) + " F" + config.boardMillVFeedRate.ToString(F,I));

                    GeneratePath(file, polygon, config.boardMillHFeedRate);

                    file.WriteLine("G0 Z" + config.clearLevel.ToString(F,I));
                }

                file.WriteLine("(stop holes milling)");
                AddStopTool(file);


            }



            /*generate board shape */
            if(outerCut != null && config.boardBorderActive)
            {
                AddToolChange(file, config.traceMillToolNumber, config.traceMillSpindleSpeed, "mill tool");
                file.WriteLine("(start board milling)");

                Polygon polygon = outerCut;
                
                file.WriteLine("G0 X" + polygon.points.Last.Value.pt.x.ToString(F,I) + " Y" + polygon.points.Last.Value.pt.y.ToString(F,I));
                file.WriteLine("G0 Z" + config.safeLevel.ToString(F,I));
                file.WriteLine("G1 Z" + config.boardMillLevel.ToString(F,I) + " F" + config.boardMillVFeedRate.ToString(F,I));

                GeneratePath(file, polygon, config.boardMillHFeedRate);

                file.WriteLine("G0 Z" + config.clearLevel.ToString(F,I));                

                file.WriteLine("(stop board milling)");
                AddStopTool(file);

            }

            /* add postamble */
            file.WriteLine("G17 G54 G90 G80 G40");
            file.WriteLine("M2");
            /*save file */
            file.Close();
        }
    }
}
